apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: editorial
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: turjacefalo/fastapi-app:COMMIT_SHA
          ports:
            - containerPort: 80
