name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-6)
          docker build -t turjacefalo/fastapi-app:${SHORT_SHA} -t turjacefalo/fastapi-app:${SHORT_SHA} .

      - name: Push Docker image (latest)
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-6)
          docker push turjacefalo/fastapi-app:${SHORT_SHA}

      - name: Push Docker image (commit tag)
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-6)
          docker push turjacefalo/fastapi-app:${SHORT_SHA}

      - name: Setup Score
        uses: score-spec/setup-score@v2
        with:
          file: score-k8s
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: score-k8s --version
      - name: Generate updated manifests
        run: |
          cd score-dev
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-6)
          score-k8s generate score.yaml \
            --image turjacefalo/fastapi-app:${SHORT_SHA} \
            --output ../manifests-score/k8s-score-manifests.yaml
          cd ..

      - name: Commit and push updated deployment.yaml
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -am "Update deployment.yaml image tag to ${SHORT_SHA}" || echo "No changes to commit"
          git push

