name: Deploy Status

on:
  repository_dispatch:
    types: [deploy-status-trigger]

jobs:
  deploy-status:
    runs-on: self-hosted
    steps:
      - name: Checkout code at commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.sha }}

      - name: Example step
        run: echo "Deploy status workflow triggered by API after build and ArgoCD sync"

# Note:
# - To trigger this workflow, make a POST request to the GitHub API:
#   POST /repos/{owner}/{repo}/dispatches
#   with JSON body: { "event_type": "deploy-status-trigger" }
# - The 'needs: build' requirement has been removed. This workflow no longer depends on the build.yaml workflow.
